import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HY | Home page",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function DemoLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
