import type { Metadata } from "next";
import { Sorts_Mill_Goudy } from "next/font/google";
import "./globals.css";
import RootProviders from "@/providers/rootProviders";

const sorts_mill_goudy = Sorts_Mill_Goudy({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "HY | Home page",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${sorts_mill_goudy.className} light`}>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
