import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import RootProviders from "@/providers/rootProviders";

const googleFont = Poppins({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "HY | Home page",
  manifest: "/manifest.json",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${googleFont.className} dark transition-colors duration-200`}
      >
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
